# Generated by Django 5.0.8 on 2025-09-08 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_userprofile_exclude_from_reporting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('training_location', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('training_date', 'training_location')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprofilecustomfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofilecustomfield',
            name='training_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.traininginfo', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilecustomfield',
            unique_together={('key_name', 'user', 'training_info')},
        ),
    ]
