# Generated by Django 5.0.8 on 2025-10-13 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_userprofile_exclude_from_reporting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Education Qualification Level'),
        ),
        
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grand_father',
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Grand Father's Name"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_post',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Health Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_post_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Health Post Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='healthpost_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Health Post UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hew_setting',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='HEW Setting'),
        ),
       
        migrations.AddField(
            model_name='userprofile',
            name='participant_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Participant ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phcu',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='PHCU Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phcu_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='PHCU UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Region UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='woreda',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Woreda'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='woreda_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Woreda UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Year of Birth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_employment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Year of Employment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Zone UID'),
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('module_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('training_date', 'module_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprofilecustomfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofilecustomfield',
            name='training_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.traininginfo'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilecustomfield',
            unique_together={('key_name', 'user', 'training_info')},
        ),
    ]
