# Generated by Django 5.0.8 on 2025-09-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_traininginfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilecustomfield',
            name='training_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.traininginfo'),
        ),
    ]
