# Generated by Django 5.0.8 on 2025-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_userprofilecustomfield_training_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininginfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='traininginfo',
            name='programme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='traininginfo',
            unique_together={('training_date', 'programme_name')},
        ),
    ]
