# Generated by Django 5.0.8 on 2025-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_userprofilecustomfield_training_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininginfo',
            unique_together=set(),
        ),
    ]
