# Generated by Django 5.0.8 on 2025-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_alter_traininginfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininginfo',
            name='module_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='traininginfo',
            unique_together={('training_date', 'module_type')},
        ),
    ]
