# Generated by Django 5.0.8 on 2025-09-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_alter_traininginfo_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininginfo',
            name='training_location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Education Qualification Level'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grand_father',
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Grand Father's Name"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_post',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Health Post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='healthpost_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Health Post UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='participant_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Participant ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phcu',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='PHCU Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phcu_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='PHCU UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Region UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='woreda',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Woreda'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='woreda_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Woreda UID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Year of Birth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_employment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Year of Employment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone_uid',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Zone UID'),
        ),
    ]
