# Generated by Django 5.0.8 on 2025-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_traininginfo_training_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profession',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_post_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Health Post Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hew_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='HEW Type'),
        ),
    ]
