# Generated by Django 5.0.8 on 2025-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_userprofile_profession_userprofile_health_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hew_setting',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='HEW Setting'),
        ),
    ]
