# Generated by Django 5.0.8 on 2025-09-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_alter_traininginfo_unique_together_and_more'),
        ('profile', '0012_userprofile_hew_setting'),
    ]

    operations = [
    ]
