# Generated by Django 5.0.8 on 2025-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_merge_20250929_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Profession',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job_title',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organisation',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Organisation Unit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='profession'),
        ),
    ]
